# Its not Numbers in Boxes its Lights in Boxes

### Group 1

## Know Your Audience (and Other Things)

- Who are your students? How many are there?
    - Second semester engineering students.
    - Have calculus I, python, matlab
    - approx 200 students
    - full course load (6 courses, cohorts)
- What is the range of prior knowledge of your students?
    - no prior linear/matrix algebra
    - computing knowledge is very minimal
- What is the format of the course? What are the constraints?
    - three 1 hours lectures per week. Large class. No computer lab. Students may have laptop/tablet.
- How will you interact with students? What is the learning management system (LMS)?
    - Live class and face-to-face office hours. Help also available from TA's in workshop.
- What computational resources are available to students?
    - Jupyter notebook through syzygy.
    - Graphing utility: Desmos/Geogebra/etc.

## Big Ideas and Essential Questions

- What’s the big idea?
    - Spanning set of a set of vectors.
- What is the core understanding that you want students to learn?
    - Given a set of vectors $\{\vec{v}_1,\ldots,\vec{v}_k\}$, and another vector $\vec{w}$ to be able to determine whether $\vec{w} \in \text{Span}(\vec{v}_1,\ldots,\vec{v}_k)$ both visually and computationally.
- What essential questions engage students with the big idea?


## Learning Goals
- What knowledge and skills should students gain from this learning experience?
    - The knowledge of what if means for a vector to be in the span of others, and the skill to read this information of from the reduced row echelon form (rref) of a matrix.
- By the end of the activity, students should know...
    - What it means for a vector to be in the spanning set
- By the end of the activity, students should be able to...
    - read this info off a rref and visually for a small dimensional example
- Are the learning goals aligned with the big idea?

## Learning Plan #
- What do you want students to do? What problem are they trying to solve?
- Are students working individually or collaboratively?
- Is the learning activity a formative or a summative assessment?
- Will students submit their work for grades?
- Is the learning plan aligned with the learning goals?
- Does the learning plan lead students to the big idea?

To do...

Include a preamble of definition of spanning set...

Consider the vectors $\vec{v}_1 = \begin{bmatrix}2\\1\\0 \end{bmatrix}$ and $\vec{v}_2 = \begin{bmatrix}1\\1\\-1 \end{bmatrix}$. We want to answer the following two questions:

1. Is $\vec{w}=\begin{bmatrix}0\\-1\\2 \end{bmatrix}$ in the span of $\vec{v}_1$ and $\vec{v}_2$?
1. Is $\vec{x}=\begin{bmatrix}2\\-1\\0 \end{bmatrix}$ in the span of $\vec{v}_1$ and $\vec{v}_2$?

### Visually:

Have a look at the following diagram. The span of $\vec{v}_1$ and $\vec{v}_2$ is shown visually as the plane. For a vector to be in the span of $\vec{v}_1$ and $\vec{v}_2$ it must lie in the plane. 

1. Does $\vec{w}$ lie in the plane?
2. Does $\vec{x}$ lie in the plane?


In [13]:
from IPython.display import IFrame
IFrame("https://www.math3d.org/5xdxEmKQur", width="100%", height="400")

From these observations, what are the answers to...

1. Is $\vec{w}$ in the span of $\vec{v}_1$ and $\vec{v}_2$?
1. Is $\vec{x}$ in the span of $\vec{v}_1$ and $\vec{v}_2$?

### Computationally

We now answer the same two questions by referring to the rref of the augmented matrix.

... need to flesh out detailed explanation here about how linear combination translates to augmented matrix...

... but jumping to code now....

In [4]:
import numpy as np

In [23]:
# implementation of a rref command since numpy/scipy doesn't have one
def rref(A, tol=1.0e-12):
    ''' input: a matrix (2D array)
       output: rref form of the matrix, and a tuple of pivot columns
    '''   
    m, n = A.shape
    i, j = 0, 0
    jb = [] # list of pivot columns

    while i < m and j < n:
        # Find value and index of largest element in the remainder of column j
        k = np.argmax(np.abs(A[i:m, j])) + i
        p = np.abs(A[k, j])
        if p <= tol:
            # The column is negligible, zero it out
            A[i:m, j] = 0.0
            j += 1
        else:
            # Remember the column index
            jb.append(j)
            if i != k:
                # Swap the i-th and k-th rows
                A[[i, k], j:n] = A[[k, i], j:n]
            # Divide the pivot row i by the pivot element A[i, j]
            A[i, j:n] = A[i, j:n] / A[i, j]
            # Subtract multiples of the pivot row from all the other rows
            for k in range(m):
                if k != i:
                    A[k, j:n] -= A[k, j] * A[i, j:n]
            i += 1
            j += 1
    # Finished
    return A, tuple(jb)

Form the augmented matrix:

In [17]:
A = np.array([[2.,1,0],[1,1,-1],[0,-1,2]])

Compute the row reduced echelon form:

In [20]:
rref(A)

(array([[ 1.,  0.,  1.],
        [ 0.,  1., -2.],
        [ 0.,  0.,  0.]]),
 (0, 1))

From the output of the calculation can we see what the solutions are to this vector equation? 

$$c_1 \vec{v}_1 + c_2 \vec{v}_2 = c_1 \begin{bmatrix}2\\1\\0 \end{bmatrix} + c_2 \begin{bmatrix}1\\1\\-1 \end{bmatrix} = \begin{bmatrix}1\\-2\\0 \end{bmatrix}$$

In [22]:
c1 = 1
c2 = -2
# verify solution
c1*A[:,0]+c2*A[:,1]

array([ 1., -2.,  0.])

Now turing out attention to vector $\vec{x}$, we again form the augmented matrix and compute the rref.

In [24]:
A = np.array([[2.,1,0],[1,1,-1],[2,-1,0]])
rref(A)

(array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]),
 (0, 1, 2))

In this case the augmented matrix has no solutions, meaning $\vec{x}$ is not in the span of $\vec{v}_1$ and $\vec{v}_2$.

### A larger dimensional example

to do...

### Application: Lights Out Puzzle

<img src="https://www.sfu.ca/~jtmulhol/math302/images/pic-puzzle-lo.png" alt="lights out" width="150"/>

This electronic puzzle consists of a 5-by-5 grid of lights; when the game starts, a set of these lights (random, or one of a set of stored puzzle patterns) are switched on. Pressing one of the lights will toggle it, and the four lights adjacent to it, on and off. The game provides a puzzle: given some initial configuration where some lights are on and some are off, the goal is to switch all the lights off, preferably in as few button presses as possible.

Try it out for yourself. Execute the following cell to load the puzzle. Use the drop down menu to select an intial configuration of lights, then try to press buttons until all the lights are off. Good luck!

In [27]:
from IPython.display import IFrame
IFrame("https://www.jaapsch.net/puzzles/javascript/lightjcl.htm", width="100%", height="200")

Let's recast this puzzle in terms of vectors. Press a button changes the state of some lights, we can record this as a vector with 25 entries (i.e. a 25-dimenstional vector) where an entry is 1 if the light in that position changes state, or 0 if it doesn't change state.

Similary we represent the starting configuration of lights as a 25-dimenstional vector where an entry is 1 if the light is on and 0 if the light is off.

To turn out the lights is equivalent to finding a linear combination of the button press vectors that sum to the starting configuration vector.

Let's do this...

To the instructor: we need to do linear algebra over GF(2) which means installing the galois package, re-executing rref, and building a solver for a linear systerm over GF(2).... best to hide all this from the student.

In [28]:
pip install galois

  Using cached galois-0.4.6-py3-none-any.whl.metadata (14 kB)
Using cached galois-0.4.6-py3-none-any.whl (4.2 MB)
Note: you may need to restart the kernel to use updated packages.


In [29]:
import galois

In [30]:
GF = galois.GF(2)

OMP: Info #276: omp_set_nested routine deprecated, please use omp_set_max_active_levels instead.


In [33]:
def rref(A):
    ''' input: a matrix over a finite field GF(p^n)
       output: rref form of the matrix, and a tuple of pivot columns
    '''   
    m, n = A.shape
    i, j = 0, 0
    jb = [] # list of pivot columns

    while i < m and j < n:
        # Find value and index of largest element in the remainder of column j
        k = np.argmax(np.abs(A[i:m, j])) + i
        p = np.abs(A[k, j])
        if p == 0:
            # The column is negligible
            j += 1
        else:
            # Remember the column index
            jb.append(j)
            if i != k:
                # Swap the i-th and k-th rows
                A[[i, k], j:n] = A[[k, i], j:n]
            # Divide the pivot row i by the pivot element A[i, j]
            A[i, j:n] = A[i, j:n] / A[i, j]
            # Subtract multiples of the pivot row from all the other rows
            for k in range(m):
                if k != i:
                    A[k, j:n] -= A[k, j] * A[i, j:n]
            i += 1
            j += 1
    # Finished
    return A, tuple(jb)

In [34]:
def lights_out(n):
    A = np.eye(n*n).astype('int16')     # initialize A with ones along diagonal
    for i in range(n):
        for j in range(n):
            m = n*i+j
            if i > 0 : A[(m,m-n)] = 1   # I block below diagonal
            if i < n-1 : A[(m,m+n)] = 1 # I block above diagonal
            if j > 0 : A[(m,m-1)] = 1   # C block below diagonal
            if j < n-1 : A[(m,m+1)] = 1 # C block above diagonal
    return A.view(GF) # convert entries to GF upon return

# Function:  number_of_presses
# input = a vector x of dimension 25 with 0,1 entries
# output = the number of times 1 appears as an entry
def number_of_presses(x):
    counter=0;
    for i in range(0,25):
        if x[i]==1: counter=counter+1
    return counter

# Function:  optimal_solution
# input = a strategy vector x
# output = an equivalent strategy vector which uses the minimum number of button presses
def optimal_solution(x):
    op_button_presses = x
    n = number_of_presses(x)
    nul = lights_out(5).null_space()
    for d in nul:
        if number_of_presses(x+d) < n:
            op_button_presses = x+d     # update variable
            n = number_of_presses(x+d)  # update variable
    return op_button_presses

def find_a_solution(M,b):
# Function:  find_a_solution
# input = matrix M, vector b
# output = one solution to Mx = b
    RR, piv = rref(np.hstack([M,b]).view(GF))
    if piv[-1] == M.shape[1]: # last column is pivot column
        return 'no solution'
    else:
        return RR[:,-1] 

# Function:  lights_out_solver
# input = b the configuration vector of lights on 5-by-5 game
# output = a matrix which solve the puzzle using the least number of button presses
def lights_out_solver(b):
    x=find_a_solution(lights_out(5),b);  # one solution
    if isinstance(x, str):
        return "no solution"
    x=optimal_solution(x)     # exchanges x for an optimal solution
    button_press_matrix = x.reshape((5,5))
    return button_press_matrix

Time for an example:

Suppose the initial configuration of lights is as follows (0=off, 1=on):

$$\begin{matrix}
1&0&0&0&0\\ 1&0&1&0&1\\ 1&0&0&0&1\\ 1&0&1&0&1\\ 0&0&0&0&1
\end{matrix}
$$

You can click "edit" in the puzzle below, set-up the lights to match this initial configuration, then click edit again to lock it in. Then try to solve it.

Here we enter it into python as a 25-dimensional vector and solve for the coeffiecients of the linear combination of button presses. The output is formatted in a way which tells you which buttons to press: 1=press, 0=don't press.

In [36]:
# Example
b=GF([1,0,0,0,0, 1,0,1,0,1, 1,0,0,0,1, 1,0,1,0,1, 0,0,0,0,1]).reshape(25,1)
lights_out_solver(b)

GF([[0, 0, 0, 1, 1],
    [1, 0, 1, 0, 0],
    [0, 0, 0, 0, 0],
    [0, 0, 1, 0, 1],
    [1, 1, 0, 0, 0]], order=2)

In [1]:
from IPython.display import IFrame
IFrame("https://www.jaapsch.net/puzzles/javascript/lightjcl.htm", width="100%", height="200")

Try out different intitial configurations of lights using the drop down menu. Then use the code window above to change b to the configuration of lights and have python compute the solution.